import { IBook } from "@/type/type";

export const data: { books: IBook[] } = {
  books: [
    {
      id: 1,
      title: "Tom, Dick and Harry",
      count: 1,
      price: 2773,
      desc: "-1E02",
      author: "Brent Washington",
      picUrl: "http://dummyimage.com/239x100.png/5fa2dd/ffffff",
    },
    {
      id: 2,
      title: "Decision at Sundown",
      count: 2,
      price: 3669,
      desc: "'\"'",
      author: "Germaine Minihan",
      picUrl: "http://dummyimage.com/209x100.png/5fa2dd/ffffff",
    },
    {
      id: 3,
      title: "Dunwich Horror, The",
      count: 3,
      price: 1751,
      desc: "œ∑´®†¥¨ˆøπ“‘",
      author: "Ingemar Grimsley",
      picUrl: "http://dummyimage.com/218x100.png/cc0000/ffffff",
    },
    {
      id: 4,
      title: "No Name on the Bullet",
      count: 4,
      price: 2362,
      desc: "הָיְתָהtestالصفحات التّحول",
      author: "Liuka Tench",
      picUrl: "http://dummyimage.com/117x100.png/ff4444/ffffff",
    },
    {
      id: 5,
      title: "Schlussmacher",
      count: 5,
      price: 2474,
      desc: "1.00",
      author: "Cirillo De'Ath",
      picUrl: "http://dummyimage.com/207x100.png/ff4444/ffffff",
    },
    {
      id: 6,
      title: "Big Fella",
      count: 6,
      price: 564,
      desc: "パーティーへ行かないか",
      author: "Reamonn End",
      picUrl: "http://dummyimage.com/113x100.png/ff4444/ffffff",
    },
    {
      id: 7,
      title: "Europa Report",
      count: 7,
      price: 3793,
      desc: "1E02",
      author: "Merola Swinburn",
      picUrl: "http://dummyimage.com/177x100.png/cc0000/ffffff",
    },
    {
      id: 8,
      title: "Girl on a Motorcycle, The",
      count: 8,
      price: 2771,
      desc: "␡",
      author: "Haven Didsbury",
      picUrl: "http://dummyimage.com/155x100.png/cc0000/ffffff",
    },
    {
      id: 9,
      title: "Maidens' Conspiracy, The (Tirante el Blanco)",
      count: 9,
      price: 3904,
      desc: 'Nice',
      author: "Merralee Thorald",
      picUrl: "http://dummyimage.com/139x100.png/5fa2dd/ffffff",
    },
    {
      id: 10,
      title: "Texas Chainsaw 3D",
      count: 10,
      price: 3620,
      desc: " ",
      author: "Salomi Dight",
      picUrl: "http://dummyimage.com/115x100.png/dddddd/000000",
    },
  ],
};
